# Makefile for my small projects
CC=gcc
CFLAGS=
all:
	$(CC) -o spacecalc spacecalc.c $(CFLAGS)
	$(CC) -o la la.c $(CFLAGS)
spacecalc:
	$(CC) -o spacecalc spacecalc.c $(CFLAGS)
la:
	$(CC) -o la la.c $(CFLAGS)
clean:
	rm -rf spacecalc la
